

# test that if the new argument is False an error is thrown
# test that if the new argument is True an error is not thrown

def test_continue_on_blacklisted_error_arg():
